### ISSUE TITLE
 Server Error 500

### ISSUE THREAD

**Issue by YevheniiVolosiuk** [pabloripoll/docker-laravel-11-php-8.3#1]
It doesn't work on Windows 10 WSL 2

![image](https://github.com/pabloripoll/docker-laravel-11-php-fpm-8/assets/77569229/95f709e3-02bf-4c00-965d-5327eb2635f5)

Also, throw an error in the Dockerfile about the existing folder

to fix it needs force creating when creating a new folder and data with a [ -f ] flag like this.

Path to file: docker/nginx-php/docker/Dockerfile

# Create symlink for php
RUN ln -sf /usr/bin/${PHP_V} /usr/bin/php

**Comment by pabloripoll** [comment]
Hi Yevhen,

The 500 error could be for some strange issue regarding the existing Laravel 11 on the repository. I removed all files and installed again and works like a charm. *(fixed it)*

Then, It is weird because every PHP Dockerfile were working perfect until two weeks ago everyone started to have the same issue. I fixed the line removing the existing file
`
RUN rm -f /usr/bin/php
RUN ln -s /usr/bin/${PHP_V} /usr/bin/php
`
But I think what you are proposing is better. So, I've just fixed it as you suggest.

The other error I don't know well what to say right now. I open the project at `http://localhost:8891` and works.

Try `$ make hostname` adding the selected port.

I don't use Windows nor WSL.

Now, I updated the repository. Clone it again and tell me how is it going.

**Comment by YevheniiVolosiuk** [comment]
> Hi Yevhen,
> 
> The 500 error could be for some strange issue regarding the existing Laravel 11 on the repository. I removed all files and installed again and works like a charm. _(fixed it)_
> 
> Then, It is weird because every PHP Dockerfile were working perfect until two weeks ago everyone started to have the same issue. I fixed the line removing the existing file `RUN rm -f /usr/bin/php RUN ln -s /usr/bin/${PHP_V} /usr/bin/php` But I think what you are proposing is better. So, I've just fixed it as you suggest.
> 
> The other error I don't know well what to say right now. I open the project at `http://localhost:8891` and works.
> 
> Try `$ make hostname` adding the selected port.
> 
> I don't use Windows nor WSL.
> 
> Now, I updated the repository. Clone it again and tell me how is it going.

After installation, http://localhost:8891 does not show anything I think it's becouse of the setup of the Windows host file and OS.

What are the purposes of using in the php dockerfile [ php83 ] prefix for extensions why just not use [ php ] ?
![image](https://github.com/pabloripoll/docker-laravel-11-php-fpm-8/assets/77569229/be0f29cb-427d-4f7e-9b48-9e4b36b1e018)

**Comment by pabloripoll** [comment]
This repository is for using Makefile for automation processes. I don't know if you're using it. If not, modify it as you pleased.

The same with ${PHP_V}. Changing that variable you can use any +8 version.

Closing issue.

Regards.
